### ISSUE TITLE
Examples needed - BusinessObject client side usage

### ISSUE THREAD

**Issue by smuemd** [energychain/StromDAO-BusinessObject#11]
Is there an example on how to invoke the BO in the browser?
I want to start simple: Just reading stuff from the Energychain.

**Comment by zoernert** [comment]
```javascript

const StromDAOBO = require("stromdao-businessobject");
var extid="IRGENDWAS";


var node = new StromDAOBO.Node({external_id:extid,testMode:true});
node.stromkonto("0xfcBfE1e0D5B62b4E281609B150423b0F15082319").then(function(stromkonto_objekt) {
	stromkonto_objekt.balancesSoll("0x0022aFE423D59a9f4AC99927a5d6D7E7c4BA017c").then(function(soll) {
      console.log("SOLL:",soll);
    });
});

**Comment by smuemd** [comment]
Yes! 
More stuff like this. We need to document this stuff more.

keeping this issue open as a reminder.
Contributors welcome!

**Comment by smuemd** [comment]
Examples update 
https://demo.stromdao.de/

Also check 
https://github.com/energychain/StromDAO-BusinessObject/wiki

Great stuff. Let's keep this going!
