### ISSUE TITLE
BO requires fs Node.js Module. Breaks in the browser

### ISSUE THREAD

**Issue by smuemd** [energychain/StromDAO-BusinessObject#12]
client side:
```js
import BO from 'stromdao-businessobject'

const myExternalID = Math.random() * 10000000
const myLedgerID = '0xfcBfE1e0D5B62b4E281609B150423b0F15082319'
const myLedgerAccountID = '0x0022aFE423D59a9f4AC99927a5d6D7E7c4BA017c'

const node = new BO.Node({ external_id: myExternalID, testMode: true })
const myLedger = node.stromkonto(myLedgerID)
```

The error:
![image](https://user-images.githubusercontent.com/3016582/27520504-80cd6ca4-5a0d-11e7-99b1-a96936390ff7.png)

This snippet must be the culprit:
![image](https://user-images.githubusercontent.com/3016582/27520519-e4d2fafc-5a0d-11e7-95dc-b1b538621ac1.png)

Maybe there can be an other way of loading the ABI files?

**Comment by zoernert** [comment]
Maybe there is another way to distinguish between "Browser" and "Node" as checking if "window" is defined. In your case it seems that "window" is not defined (which should be in case of browser usage). This might be a bug of the build environment/packaging as it does not meet the condition. 

What other object might be used instead?

**Comment by smuemd** [comment]
The Node.js API has the method process.plattform,
So we we might be able to test for `process.platform == "browser"`. => https://nodejs.org/api/process.html#process_process_platform

Using Browserify we could also test against `process.browser == true`. => https://www.npmjs.com/package/process


However, I think there is no need to optimize the BO for module bundlers at this time point. We should focus on making it work in node.js (server side) and as a standalone script to be included in HTML (client side).

This standalone browser bundle could be made available in a dist folder for example so that it is easy to find and consume.

**Comment by smuemd** [comment]
Anyway, so this might fix it:

```js
If (process.plattform !== 'browser') { 
    const fs = require('fs')
}

```

**Comment by zoernert** [comment]
process is not available in standard Javascript as implented in browsers ... but a solution via DIST-folder might be a good idea.

**Comment by smuemd** [comment]
This was resolved: Proper way to use BO in browser: 
HTML

```html
<script src="https://cdn.rawgit.com/energychain/StromDAO-BusinessObject/master/dist/loader.js"></script>
```

Javascript
```js
// Create Instance with external ID 1234
var node = new document.StromDAOBO.Node({
 external_id:"1234",
 testMode:true,
 rpc:"https://demo.stromdao.de/rpc=",
 abilocation:"https://cdn.rawgit.com/energychain/StromDAO-BusinessObject/6dc9e073/smart_contracts/"
}); 
```
Interactive showcase here: https://demo.stromdao.de/showcase/sc1_frm.html
