### ISSUE TITLE
error on initial load in browser

### ISSUE THREAD

**Issue by smuemd** [energychain/StromDAO-BusinessObject#13]
I am using the [loader.js bundle](https://unpkg.com/stromdao-businessobject@0.4.7/dist/loader.js) in a browser.

On first load I get the following error:
![image](https://user-images.githubusercontent.com/3016582/27614936-078e2880-5ba5-11e7-9063-9a8013689e0c.png)

After refreshing the page. It works fine.

I reproduced this across two different apps both using the BO loader lib. Looks like a hick up with the RPC reference. Any thoughts?

**Comment by zoernert** [comment]
Fixed with latest commit. 

Loader JS got fixed in previous dapp commit.
