### ISSUE TITLE
stromkontoproxy vs stromkonto

### ISSUE THREAD

**Issue by smuemd** [energychain/StromDAO-BusinessObject#20]
I have the following snippet in a settlement script that got injected in a mpo store comand:
![image](https://user-images.githubusercontent.com/3016582/32750024-98f4f2ca-c8c1-11e7-897c-15ccd9fbb939.png)
This caused the following error:
![image](https://user-images.githubusercontent.com/3016582/32750053-b540c0d0-c8c1-11e7-9b42-f9faffda22f9.png)
When I changed stromkontoproy to stromkonto. I went through without error.
![image](https://user-images.githubusercontent.com/3016582/32750263-6e940074-c8c2-11e7-9459-4beeda059fc9.png)

using 
```
   "stromdao-bo-mpo": "0.2.29",
    "stromdao-businessobject": "0.5.19"
```

**Comment by zoernert** [comment]
The issue is related to array type return. 
Please use `global.smart_contract_stromkonto[0]` in your  not working case.
