### ISSUE TITLE
How to access the IPFS System

### ISSUE THREAD

**Issue by MrMoehner** [energychain/StromDAO-BusinessObject#21]
Dear Sir or Madam, 

when i do a transaction, say saving a meter value, i get a transaction code back.

As far as i understand,  the blockchain is used for the validation and IPFS System for storage (database). Can you give me a hint how it actually works and how i can "see" the stored data or get acces to them?

I also want to see the block itself. Face to face to the blockchain. I did not find any method on the main object to read this information out. 

Thanks and regards, 

Lukas

**Comment by zoernert** [comment]
The transaction hash is not related to IPFS. It is pure ID of you blockchain transaction if you install a full node (or via the Business Object) you could retrieve transactions by ID per block.

In abstraction you could use the library behind your node.wallet objects which is ethers.js:
https://docs.ethers.io/ethers.js/html/

in particular you might want to use the following functions:
https://docs.ethers.io/ethers.js/html/api-providers.html#blockchain-status
