### ISSUE TITLE
Add DirectCharging Capabilities (IoT)

### ISSUE THREAD

**Issue by zoernert** [energychain/StromDAO-BusinessObject#9]
Direct Charging is the possibility to set a cost information directly based on sequential meter readings and charge them to a stromkonto.

**Comment by smuemd** [comment]
This would be like an extension of the mprReadingGenesis contract: Providing not just the capability to submit meter readings without MPO, and DSO contracts for testing purposes; but also to directly charge money based on such readings (power consumed).

Questions: 
Will powerDeliverables be created in the process?
What event will trigger the billing? And what happens to powerDeliverables, if created, at billing.

How does the IoT use case fit into the picture here?
I assume this will have to work completely separated from normal consensus metering and billing intended for testing only.

**Comment by zoernert** [comment]
> Will powerDeliverables be created in the process?
No billing is done per meter reading directly to the stromkonto account(s) associated

> What event will trigger the billing? 
Contract:DirectCharging.chargeAll() - needs to be triggered by issuing a transaction

> How does the IoT use case fit into the picture here?
This is designed to work in IoT environments without trading and without having a consens over all aspects of a grid (eq. uncomplete grid)

**Comment by zoernert** [comment]
Solved in alignment to https://github.com/energychain/stromdao-dapp
